name: data512_project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - -r requirements.txt
prefix: /opt/miniconda3/envs/data512_project
